### ISSUE TITLE
[not an issue] Simple requests

### ISSUE THREAD

**Issue by EstherMoellman** [billdoor1/javascript_firewall#1]
Hi @billdoor1 !

Firstly, let me thank you for answering my review at your Mozilla AMO' page (25 days ago). You promptly fulfilled some of my requests there. Also, thank you for your GitHub repo, it allows better interaction with you.

For the last 25 days I'm using your add-on. And I want to say: It's a W-O-N-D-E-R-F-U-L add-on! Amazing! A little powerful gem. Congrats! Excellent job.
In one hand it is very lightweight, and in the other hand it is extremely powerful.
Your add-on replaces me at least 6 other blocker-add-ons. Your add-on is the perfect killer for webgarbage, while improving browser performance. I tested it against UMatrix, and in my opinion, your add-on is a winner (almost same blocking power than UMatrix, but with just a fraction of browser resources).
Perhaps your add-on needs a push in its marketing, users are not aware that your add-on easily may replace tons of other blocker add-ons.

Now, and back to my requests for your add-on, please if you can, it will be great to add:
1) Badge (at icon navbar) counting blocked items.
2) Expanding the blocking matrix to other categories (cookies, plugin-handled-content, service workers, etc).
3) At "options" page, the possibility of using RegExps as blocking rules.

I don't expect you to attend my requests immediately. Please, take all the time you need.
It will be a challenge for you, to expand blocking capabilities, while preserving browser performance.
However, if you can do that, wow, your add-on is going to be even more wonderful than is now, in my opinion one of the best add-on out there. 

Thank you in advance!

**Comment by billdoor1** [comment]
Thanks :)
Yes i wanted make an little addon like UMatrix with only some of its features.

1. Version 1.2 now has the badge counter.


2. The workers are blocked by the "JS" column and plugins by the "FRAME" column.
- JS column => javascript code: either from <script> or workers
- XHR column => requests made by the page: XMLHttpRequest,WebSocket,Beacon,ping,Content-Security-Policy-report
- FRAME column => external content: `<frame>`,`<iframe>`,`<object>`,`<embed>` (`<object>` and `<embed>` are used for include plugins)

The matrix would end up with too many columns if each categorie had its own column.
It's less customizable with 3 columns but i don't think it worth adding more columns.

Currently, there is a tooltip on the "JS", "XHR" and "FRAME" cells which indicates what is blocked by the column. Maybe i should find a better way to inform the user what is blocked by a column.

For the cookies, there isn't a good way to block them with webextension.
Either by doing as UMatrix and block them in the HTTP request header but they still exist in the browser and javascript code can access them.
Or remove them from the server HTTP response header but cookies can still be created by javascript code. So it's not simple. I prefer to let the browser settings or other addons handle the cookies.


3. Can you give an example of regexp you would want?

**Comment by EstherMoellman** [comment]
@billdoor1 thanks for you answer and for the new version 1.2... I loved it! (PS: The badge may start counting from "1", the "0" seems to me unnecessary/distracting).

I perfectly understand that the matrix may become giant, and you want to keep everything compact..
But as an idea, perhaps you can steal from UMatrix the concept of adding buttons (on/off) for some stuff (not JS, not XHR, not FRAME), like workers, objects etc. So, you may keep the current matrix, which will distribute blocked items among the 3 columns, but in parallel, also you may add some buttons in order to allow the user to easily unblock this stuff. It is just an a idea.

IMO the challenge is:
1) To keep a compact matrix of 3 columns
2) To block as much as possible elements, inside these 3 columns
3) To allow some easy access to not JS, not XHR, not FRAME elements
Items "1" and "2" you already achieved (kudos).
For item "3", perhaps the on/off buttons idea may work. You have the last word!

With regards to the cookies, I really don't like the FF' built-in options, because IMO they are full of bugs.
Think with me @billdoor1 , if the FF' built-in cookies blocker were working well, why cookie-blocker-addons were needed?
Why UMatrix has its own cookie blocker? (Gorhill is a genius, and he knows what he is doing).
Why [PrivacyPossum](https://addons.mozilla.org/en-US/firefox/addon/privacy-possum/) also has its own cookie blocker?
Etc?

I understand you want to keep your JSF simple and minimalist.
But from my user point of view, I'm trying to see your JSF as my complete solution for blocking webgarbage.
And considering cookies are the main vector for tracking... it will be a dream if your JSF can do something to block them.
Always remembering that the less add-ons the better, so that's the reason I'm trying to convince you to hardening a bit your JSF. And blocking cookies in one of the hardening way.

The second hardening way is RegExps.
By adding this capability to your JSF, no ad-blockers will be needed!
This is the last huge complement to your JSF.
PS: Blocking-lists are browser performance killers, but RegExps work like a charm.

IMO, the current JSF is great mainly as a security tool, because may blocks lot of undesirable JS.
My suggestions to you are trying to harden the privacy strength side of JSF, by blocking cookies.
And RegExps blocking ads will harden both, security and privacy.
This is my personal vision of your great JSF... a tiny lightweight add-on, but powerful at security, privacy, tracking, ads etc, replacing tons of other add-ons.
... it will be the dreamed add-on IMO!
And browser performance will be fantastic.

Important to say that even if you don't accept my suggestions/logic, your current JSF is FANTASTIC!, I'm totally in love with it. A gem. I can't see myself back to dinosaurs like UBlock, UMatrix etc.
Excellent job! Congrats again!

Thousand thanks to you in advance!

PS: [Here are some of the RegExps](https://pastebin.com/YfB4S2vR) I would like to use inside JSF. Presently I'm using these RegExps with [this add-on](https://addons.mozilla.org/en-US/firefox/addon/rule-adblocker/). These RegExps block the pesky ads embedded in first-party elements, that your JSF can't block because breaks webpages.

**Comment by billdoor1** [comment]
Ah yes, I agree. Display the badge when nothing is blocked is useless. I'll change that.

The problem with a on/off menu like UMatrix is that some requests may be blocked even if the matrix is full green. I want the addon to clearly shows what is blocked/allowed so i don't want add blocking control outside the matrix.
About, object/embed, is there a case where someone would want to allow iframe/frame on a domain but not object/embed ? It is almost the same thing for me.

For the regexps, the problem is the matrix could be full green but a request may still be blocked by a regexp. Having two blocking methods which can conflict with each other will make the addon confusing. I don't see a good way to add regexps while keeping the interface simple and clear. Given the very few ads not blocked by the addon, i don't think that worth it. The only really annoying ads i still see with the addon are on Youtube but i block them with the addon [AdBlocker for YouTube](https://addons.mozilla.org/fr/firefox/addon/adblock-for-youtube/). 

For the cookies I haven't noticed any bug in the Firefox settings,  even though the user interface is pretty bad. If you select "block third party cookies" all the trackings cookies/storage will be blocked. If Firefox adds an API to access the cookie whitelist then I may add a cookie column to easily add/remove a website in one click. But right now I think the webextension API for cookies handling sucks :/

I want to keep a good balance between blocking power, clarity and simplicity. The goal is not to replace all the other addons related to blocking/privacy. Some features will be missing for some users but then it's possible to complete JSF with other addons like your "Rule AdBlocker" and a cookie/storage one.

**Comment by EstherMoellman** [comment]
Hi @billdoor1 ,

I understood your logic of keeping a clear information between the matrix and what is blocked/unblocked.
But my feeling is that the matrix (graphic interface) should not limit blocking/unblocking functions.
In simple words, for example, if an ad is blocked at first-party, and at the matrix this first-party is green... well, honestly, I don't care! I rather care about the ad being blocked! But this is my personal opinion.
In the worst case, I will be happy if:
a) The counter badge shows total blocked elements.
b) The matrix remains as current.
c) A new tab is added at the menu popup (or at "options"), with on/off buttons for each not detailed element at the matrix (workers, object, RegExps etc). Also in this tab, at each "on" button, a counter may show the total of blocked elements.
d) RegExps will demand another third tab inside the menu popup. But also, a counter may be added, showing total of blocked elements.

So, based in my idea above, the user may not know exactly what element those buttons are blocking, but at least the user:
1) Will be able to block/unblock these elements.
2) Will see the total counter of blocked elements (if the button is "on").
Therefore, my idea may not be perfect, but is a progress when compared to present situation.

With regards to you first question, I don't really have enough knowledge to answer. But as an user, by experience, I can tell you that in general add-ons have separated categories for blocking (for example, frames separated from object). Here you have an example with [this addon](https://addons.mozilla.org/en-US/firefox/addon/policy-control/). Also this add-on, may inspire you with the buttons idea.

With regards to ads, what you see and don't see depends a lot on what you block or unblock at your add-on.
In my personal opinion, average users are not going to use your add-on for first-parties. Most of them will use for blocking third-party, specially JS. This is because blocking first-party will break too much webpages.
And enabling first-party + some third-party... may open the doors of the ads hell.
That is why RegExps may be a powerful complement for your add-on.

You may not noticed problems with cookies, but if you go to bugzilla... you will see tons of bugs... some of the bugs are many years old.

My final words:
I repeat, your add-on as it is now... already is a gem.
So, don't worry too much about my requests.
Feel free to use my requests as "mind food"... ideas that you may or may not take advantage.
If you are comfortable with your current add-on... that's enough.
But if you want to keep developing your add-on, then feel free to take advantage of my requests as a kind of inspiration for you.

PS: I'm not sure, but it seems to me that the "Disable/Enable" button is not working for "all websites". I say "I'm not sure" because I only tested one device and Nightly.
